/* Generated By:JJTree: Do not edit this line. ASTconstant.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package at.ac.univie.philo.mmr.server.parsetree;

public
class ASTconstant extends SimpleNode {
	
	String name;
	Integer index = 0;
	
	
  public ASTconstant(int id) {
    super(id);
  }

  public ASTconstant(crflang p, int id) {
    super(p, id);
  }
  
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getIndex() {
		return index;
	}

	public void setIndex(String stringIndex) {
		try {
			int intIndex = Integer.parseInt(stringIndex);
			this.index = intIndex;
		} catch (NumberFormatException e) {
				System.err.print("Could not parse Index of Variable");
		}
	}


  /** Accept the visitor. **/
  public Object jjtAccept(crflangVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=fb197ded340a34b6465180a6a1596ce1 (do not edit this line) */
