/* Generated By:JJTree: Do not edit this line. ASTfunctionname.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package at.ac.univie.philo.mmr.server.parsetree;

public
class ASTfunctionname extends SimpleNode {
	
	Integer arity;
	Integer index = 0;
	private String name;
	
  public ASTfunctionname(int id) {
    super(id);
  }

  public ASTfunctionname(crflang p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(crflangVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }

public Integer getArity() {
	return arity;
}

public Integer getIndex() {
	return index;
}

public void setArity(String stringArity) {
//	try {
		int intArity = Integer.parseInt(stringArity);
		this.arity = intArity;
//		} catch (NumberFormatException e) {
//			System.err.print("Could not parse Index of Variable");
//		}
}

public void setIndex(String stringIndex) {
	try {
		int intIndex = Integer.parseInt(stringIndex);
		this.index = intIndex;
		} catch (NumberFormatException e) {
			System.err.print("Could not parse Index of Variable");
		}
}

public void setName(String image) {
	this.name = image;
}

public String getName() {
	return name;
}

}
/* JavaCC - OriginalChecksum=6be30f6bdc0a807357c2deb168c507f9 (do not edit this line) */
