/* Generated By:JJTree: Do not edit this line. ASTvariable.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package at.ac.univie.philo.mmr.server.parsetree;

public
class ASTvariable extends SimpleNode {
	
	String name;
	Integer index = 0;
	
  public ASTvariable(int id) {
    super(id);
  }

  public ASTvariable(crflang p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(crflangVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }

public String getName() {
	return name;
}

public Integer getIndex() {
	return index;
}

public void setName(String name) {
	this.name = name;
}

public void setIndex(String stringIndex) {
	try {
	int intIndex = Integer.parseInt(stringIndex);
	this.index = intIndex;
	} catch (NumberFormatException e) {
		System.err.print("Could not parse Index of Variable");
	}
}

}
/* JavaCC - OriginalChecksum=a19a859f3026d07a77ba883fde91dfe5 (do not edit this line) */
