/* Generated By:JavaCC: Do not edit this line. crflangTreeConstants.java Version 5.0 */
package at.ac.univie.philo.mmr.server.parsetree;

public interface crflangTreeConstants
{
  public int JJTEXPRESSION = 0;
  public int JJTVOID = 1;
  public int JJTTRUTHVALUE = 2;
  public int JJTBICONDITIONAL = 3;
  public int JJTNEGATION = 4;
  public int JJTCONJUNCTION = 5;
  public int JJTDISJUNCTION = 6;
  public int JJTIMPLICATION = 7;
  public int JJTXOR = 8;
  public int JJTVARIABLE = 9;
  public int JJTPREDICATE = 10;
  public int JJTPREDICATENAME = 11;
  public int JJTCONSTANT = 12;
  public int JJTFUNCTION = 13;
  public int JJTFUNCTIONNAME = 14;
  public int JJTALLQUANTOR = 15;
  public int JJTEXISTENCEQUANTOR = 16;
  public int JJTBOX = 17;
  public int JJTDIAMOND = 18;


  public String[] jjtNodeName = {
    "expression",
    "void",
    "truthvalue",
    "biconditional",
    "negation",
    "conjunction",
    "disjunction",
    "implication",
    "xor",
    "variable",
    "predicate",
    "predicatename",
    "constant",
    "function",
    "functionname",
    "allquantor",
    "existencequantor",
    "box",
    "diamond",
  };
}
/* JavaCC - OriginalChecksum=eedd55b9d3e22cd40a22838e8bcc3824 (do not edit this line) */
