/* Generated By:JJTree&JavaCC: Do not edit this line. crflangConstants.java */
package at.ac.univie.philo.mmr.server.parsetree;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface crflangConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INT = 14;
  /** RegularExpression Id. */
  int NAME = 15;
  /** RegularExpression Id. */
  int FNAME = 16;
  /** RegularExpression Id. */
  int OR = 17;
  /** RegularExpression Id. */
  int AND = 18;
  /** RegularExpression Id. */
  int NOT = 19;
  /** RegularExpression Id. */
  int XOR = 20;
  /** RegularExpression Id. */
  int EXISTS = 21;
  /** RegularExpression Id. */
  int FORALL = 22;
  /** RegularExpression Id. */
  int IMPLICATION = 23;
  /** RegularExpression Id. */
  int BICONDITIONAL = 24;
  /** RegularExpression Id. */
  int TRUE = 25;
  /** RegularExpression Id. */
  int FALSE = 26;
  /** RegularExpression Id. */
  int BOX = 27;
  /** RegularExpression Id. */
  int DIAMOND = 28;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\r\"",
    "\"(\"",
    "\")\"",
    "\"x\"",
    "\"y\"",
    "\"z\"",
    "\"_\"",
    "\",\"",
    "\"^\"",
    "\"a\"",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "<INT>",
    "<NAME>",
    "<FNAME>",
    "\"\\\\vee\"",
    "\"\\\\wedge\"",
    "\"\\\\neg\"",
    "\"\\\\oplus\"",
    "\"\\\\exists\"",
    "\"\\\\forall\"",
    "\"\\\\rightarrow\"",
    "\"\\\\leftrightarrow\"",
    "\"\\\\top\"",
    "\"\\\\bot\"",
    "\"\\\\box\"",
    "\"\\\\diamond\"",
  };

}
