/* Generated By:JavaCC: Do not edit this line. crflangVisitor.java Version 5.0 */
package at.ac.univie.philo.mmr.server.parsetree;

public interface crflangVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTexpression node, Object data);
  public Object visit(ASTtruthvalue node, Object data);
  public Object visit(ASTbiconditional node, Object data);
  public Object visit(ASTnegation node, Object data);
  public Object visit(ASTconjunction node, Object data);
  public Object visit(ASTdisjunction node, Object data);
  public Object visit(ASTimplication node, Object data);
  public Object visit(ASTxor node, Object data);
  public Object visit(ASTvariable node, Object data);
  public Object visit(ASTpredicate node, Object data);
  public Object visit(ASTpredicatename node, Object data);
  public Object visit(ASTconstant node, Object data);
  public Object visit(ASTfunction node, Object data);
  public Object visit(ASTfunctionname node, Object data);
  public Object visit(ASTallquantor node, Object data);
  public Object visit(ASTexistencequantor node, Object data);
  public Object visit(ASTbox node, Object data);
  public Object visit(ASTdiamond node, Object data);
}
/* JavaCC - OriginalChecksum=09123c9cc3fdf4fb858028ca831bdd6b (do not edit this line) */
