/* Generated By:JJTree: Do not edit this line. ASTexistencequantor.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package at.ac.univie.philo.mmr.server.parsetree;

public
class ASTexistencequantor extends SimpleNode {
  public ASTexistencequantor(int id) {
    super(id);
  }

  public ASTexistencequantor(crflang p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(crflangVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=59b1e574825aa4e499b261a85a3b0cfd (do not edit this line) */
