/* Generated By:JJTree: Do not edit this line. ASTtruthvalue.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package at.ac.univie.philo.mmr.server.parsetree;

public
class ASTtruthvalue extends SimpleNode {
 
	private boolean truthvalue;
	
	public ASTtruthvalue(int id) {
    super(id);
  }

  public ASTtruthvalue(crflang p, int id) {
    super(p, id);
  }
  
  public void setValue(String val) {
	  if (val.equalsIgnoreCase("TRUE")) {
		  this.truthvalue= true;
	  } else if (val.equalsIgnoreCase("FALSE")){
		  this.truthvalue = false;
	  }
  }
  
  public boolean getValue() {
	  return this.truthvalue;
  }


  /** Accept the visitor. **/
  public Object jjtAccept(crflangVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=78555bafd0fdc58d3d6490d692e12b69 (do not edit this line) */
